### ISSUE TITLE
Figure out way to reduce database row count to <= 10,000

### ISSUE THREAD

**Issue by jacksonyuanjx** [ubclaunchpad/life-at-ubc#106]
* Heroku Postgres has a limit of 10k rows for the free tier and currently our app only uses one endpoint so maybe we could reduce the data inserted into the DB

**Comment by johnagl** [comment]
This is a random thought, but could we somehow use 2-3 databases? Lol.

**Comment by johnagl** [comment]
Also @jacksonyuanjx you mentioned CDN before. How does that work exactly?

**Comment by jacksonyuanjx** [comment]
I'm not sure if the free Heroku plan supports that but we could try? Although I was thinking it might not be ideal to have multiple databases to store each of our tables.

As for using a CDN, we would just upload our data (e.g. as a JSON file) and serve it through a CDN provider. On the front-end we would just make a request to retrieve this data so we have access to it. We could also separate out each table into a separate file. Hopefully that'll greatly reduce the size.

**Comment by johnagl** [comment]
> I'm not sure if the free Heroku plan supports that but we could try? Although I was thinking it might not be ideal to have multiple databases to store each of our tables.
> 
> As for using a CDN, we would just upload our data (e.g. as a JSON file) and serve it through a CDN provider. On the front-end we would just make a request to retrieve this data so we have access to it. We could also separate out each table into a separate file. Hopefully that'll greatly reduce the size.

This makes me so sad. If we take this approach we would not need a server at all.

**Comment by resurl** [comment]
iirc, we have 3 tables but 2 of them aren't being used (coreq/prereq tables). i think we'd only need those tables if we ever allow users to log in and store their past course information (so that they can ask if specific course requirements are fulfilled), so maybe we can drop those tables?

**Comment by johnagl** [comment]
> iirc, we have 3 tables but 2 of them aren't being used (coreq/prereq tables). i think we'd only need those tables if we ever allow users to log in and store their past course information (so that they can ask if specific course requirements are fulfilled), so maybe we can drop those tables?

Getting rid of the 2 tables would get us down to about 19k rows. The coursesection table alone has over 19k rows...

**Comment by resurl** [comment]
oh god

**Comment by resurl** [comment]
i could change the scraper to take out directed studies/courses without a start/end time since they won't appear on the schedule anyway? kind of doubt that it would reduce the rows by half though, but i'll try it tonight :')

**Comment by johnagl** [comment]
Haha sure that could work. I think our biggest issue is that every section is it's own row. It would be much much better if there was only 1 row for a given course. I'm not sure if this is possible with Postgres and I think we may have discussed this before - but would be nice if we could have 1 key represent "sections" and its value being an array of objects with the specific section information. I know this is possible on MongoDB.

**Comment by resurl** [comment]
an update on this: i changed the scraper to exclude courses/sections without a start or end time and the # of rows decreased from 19k to 13k. it's still pretty far from the limit so i checked out postgres json types and we [should be able to store and access json arrays](https://levelup.gitconnected.com/working-with-a-jsonb-array-of-objects-in-postgresql-d2b7e7f4db87). im not too familiar with SQL but i'll try to implement the code this week!

**Comment by johnagl** [comment]
> an update on this: i changed the scraper to exclude courses/sections without a start or end time and the # of rows decreased from 19k to 13k. it's still pretty far from the limit so i checked out postgres json types and we [should be able to store and access json arrays](https://levelup.gitconnected.com/working-with-a-jsonb-array-of-objects-in-postgresql-d2b7e7f4db87). im not too familiar with SQL but i'll try to implement the code this week!

AWESOME!!! It looks like we have a solution to our problem then.
