### ISSUE TITLE
React router

### ISSUE THREAD

**Issue by aldy97** [ubclaunchpad/life-at-ubc#107]
Even though the navigation bar doesnt do anything for now, but rather than using window.href in order to navigate into different pages should we use Redirect provided by react-router-dom in order to avoid page refresh so that we could make it a SPA. This also improves user experience.

**Comment by johnagl** [comment]
Okay, I don't really understand what this one is...

**Comment by aldy97** [comment]
@johnagl using window.location.href causes re-initiation of redux store
