### ISSUE TITLE
Fix lab section layout, selection of labs

### ISSUE THREAD

**Issue by johnagl** [ubclaunchpad/life-at-ubc#120]
Fix lab sections screen:
1) Layout should closely resemble wireframes
2) Selected lab section should appear on schedule and the tab should appear selected/highlighted. Right now the lab section gets added but the tab isn't highlighted
3) Add feature to deselect as mentioned by @yehee in #123

Question for designers:
1) Should we even display lab sections that overlap with current courses? If yes, how should we show that they overlap? 

Wireframes:
![labSection](https://user-images.githubusercontent.com/42220961/106091862-179d6b00-60e2-11eb-9efd-9d6c5f33d351.png)

Actual:
![labSection2](https://user-images.githubusercontent.com/42220961/106091941-369bfd00-60e2-11eb-83d7-5e10a6c1a5af.png)

**Comment by johnagl** [comment]
From meeting: 

- display all lab sections even if they overlap with selected sections
- on hover, show course on the schedule to see if it overlaps (like how ssc does it), I think this should be possible with our current setup, but if not we can think of other ways to indicate overlaps

**Comment by yehee** [comment]
I might take over this issue unless anyone else has already worked on it.
