### ISSUE TITLE
Improve lecture screen, timetable/grid UI

### ISSUE THREAD

**Issue by johnagl** [ubclaunchpad/life-at-ubc#121]
1) Attempt to avoid scrollbar of schedule grid (like in the wireframes). We probably have to increase the size that the schedule grid takes up and perhaps remove unnecessary times (eg. not a lot of evening classes so don't show on default?).

2) Add feature to "lock in" course. Courses should stay locked as you navigate through schedules (eg. 1-10). Note that recomputation of valid schedules will happen. For example, if I locked CPSC 310 203, then the subsequent schedules should no longer have CPSC 310 sections, or any other sections that overlap with 203.

3) Add feature to "de-lock" course

Designers:
1) Thoughts on having too many times on the schedule grid/ the scroll bar?

Wireframes:
![lectureWireframe](https://user-images.githubusercontent.com/42220961/106092506-436d2080-60e3-11eb-9060-a69cdd403e9e.png)

Actual:
![lectureActual](https://user-images.githubusercontent.com/42220961/106092521-4ec04c00-60e3-11eb-8d03-2545e4d2cb75.png)

**Comment by johnagl** [comment]
Default time range should be 8am - 3pm. Only include evening times if there is a course during that time frame.

**Comment by yehee** [comment]
I can continue working on this once the design decision is made further.

**Comment by yehee** [comment]
@nico-zhu @sarahdang I'm thinking we need some sort of indication when there are no schedules that meet the criteria. Right now the page goes blank with no suggestions for users! Would this be something that we could work on? I could also just come up with a simple indicator with some icon and message 👍

**Comment by yehee** [comment]
@johnagl What else needs to be worked on for this task?

**Comment by johnagl** [comment]
@yehee I think this one is done!
