### ISSUE TITLE
The concept of selecting timetable needs to be refined

### ISSUE THREAD

**Issue by yehee** [ubclaunchpad/life-at-ubc#122]
- Right now, the user goes through the available options in the paginated pages, and settle on one
- Perhaps a lock or select button next to the timetable?

**Comment by johnagl** [comment]
I like this idea. Perhaps we should force the user to lock a schedule before allowing them to proceed to the next page. Progression through screens is also up for discussion in #117 :)

**Comment by johnagl** [comment]
So we discussed this in the meeting today - and discussed how it's implicitly indicated that by moving to the next screen you're locking in the schedule. So we thought that we probably don't need a button to lock a schedule? 

I'm not sure we understood this issue completely..

**Comment by yehee** [comment]
Closing it for now; reopen it if we decide to create a button to explicitly select a schedule.
