### ISSUE TITLE
User should only select one lab/tutorial section per course

### ISSUE THREAD

**Issue by yehee** [ubclaunchpad/life-at-ubc#125]
- How to implement it using chips?
- Perhaps switch it to dropdown list?

**Comment by johnagl** [comment]
My initial thoughts:

1) Dropdown would easily solve the issue of only selecting one lab/tutorial and we wouldn't have to do too much validation. However, I think chips are nicer (UI wise).

2) We might be able to implement this with chips by keep track of whether we have selected a tutorial/lab for a given course (eg. in Redux state). If we have already selected a tutorial/lab, then selecting a different one would just replace the current selection. 

As an aside, I was also thinking that hovering over chips should show where the tutorial/lab would take place on the schedule (sort of like how worklists work on SSC). <- Not sure this is possible yet and might be worth looking into in a new issue.
