### ISSUE TITLE
Learn Git

### ISSUE THREAD

**Issue by johnagl** [ubclaunchpad/life-at-ubc#13]
1. Learn about Git/Github workflows if you aren't familiar with it already (https://docs.ubclaunchpad.com/resources/git-workflow).

For practice:
1. Clone repo, make sure frontend and server are running properly (see README)
2. Create a new branch, make a small change in source code (eg. change what the frontend displays)
3. Push your branch 
4. Create a PR and tag @johnagl as a reviewer

**Comment by aldy97** [comment]
Done!

**Comment by danielchen-pyc** [comment]
Done!
