### ISSUE TITLE
Add Session to "Choose Term" Screen

### ISSUE THREAD

**Issue by johnagl** [ubclaunchpad/life-at-ubc#134]
Right now, we've hardcoded "Term 1" and "Term 2" assuming that the session is the current Winter session. We should display the session to notify the user (for example, current session we're on is Winter 2020).

![SessionUBC](https://user-images.githubusercontent.com/42220961/108793622-ccd40f00-7538-11eb-9267-c43033f13806.png)

Looking at the current database schema, it looks like we don't have session stored anywhere so we may have to add another column. 

Let me know what you guys think!

Unfortunately I don't think we have enough database space to store 2 session (ie: both Winter 2020 and Summer 2021). I think that should be fine though since most people aren't going to be using a scheduler for previous/current terms (only future ones). We also talked about this before if I'm not mistaken.

**Comment by yehee** [comment]
@resurreccionl Depending on how much effort this would take, I'm not sure if this is something that's worth scraping from the website. Can we just have an env var to keep track of this since users have no choice over this? thoughts?

**Comment by resurl** [comment]
@yehee it might be a bit tedious to scrape it, but it shouldn't be too bad i think? i'm curious what you mean by having an env var keeping track of it though, do you mean just manually keeping track of the session information or whether the database information is old or something like that?

**Comment by yehee** [comment]
@resurreccionl I wasn't sure how we'd be storing that piece of information on DB, and yeah! Definitely not the most favorable to keep it around as an env var, just wondering if that would just be a quick solution to this.

**Comment by johnagl** [comment]
Okay so thought about this a bit more. We can probably just hard code session on the frontend. We might not need to actually scrape it or change db schema like I initially said. It can work something like this: 

1) Display session on frontend (eg. Winter 2020)
2) When we update database - remove all previous/current course information
3) Then add all course information for future terms (eg. Summer 2021)

This way, we don't have to store session in the database since we can just first delete all courses in the database when we update. I think this works? @resurreccionl @yehee 

This simplifies #135 as well.

**Comment by resurl** [comment]
i think im just really hesitant about needing to manually change the session value, since someone would need to remember to change the display from Winter 2020 -> Summer 2021 and so on LOL (unless im understanding this wrong)

doing that would definitely be quicker though for sure. 
also, i think in the current setupDB, i drop all tables every time the scraper runs, so that's # 2 done already
