### ISSUE TITLE
Saving Methods

### ISSUE THREAD

**Issue by resurl** [ubclaunchpad/life-at-ubc#140]
we discussed two types of saving today! pls comment what you think about the two methods and/or which one you prefer @johnagl @yehee @nico-zhu @danielchen-pyc 

## Shareable Links
After generating and selecting a schedule from Courseload, the user has the option of saving the schedule via a link (something like `courseload.com/saved/:id`). This link allows them to share their selected schedule with others. They'll have to click a save button on the selected schedule or something along those lines to get this link. 

## Worklist Saving
Mentioned in issue #59. We can allow users to save a schedule by generating links of the form
```
courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-course&dept=[COURSECODE]&course=[COURSENUMBER]&submit=save
```
for each course. Once the user has logged in the SSC and selected the right worklist to save to, we provide a button that redirects them to each of those links and it'll save all courses to that worklist.

(let me know if i missed anything!!)

**Comment by johnagl** [comment]
I think the worklist saving is pretty useful, and implementation will be relatively easy (just frontend work). @nico-zhu @sarahdang any comments on these from a design perspective?

**Comment by johnagl** [comment]
@resurreccionl It looks like we're going with shareable link - might be able to do this without having to store stuff into the DB. I'm looking at this now in #146

**Comment by resurl** [comment]
> @resurreccionl It looks like we're going with shareable link - might be able to do this without having to store stuff into the DB. I'm looking at this now in #146

okay sounds good! i'll close the issue then
