### ISSUE TITLE
Production Version Had Empty DB

### ISSUE THREAD

**Issue by johnagl** [ubclaunchpad/life-at-ubc#142]
Got this email earlier: 
![chronfail](https://user-images.githubusercontent.com/42220961/109577743-f4802580-7aaa-11eb-8784-f4ecac9a6acf.png)

Went on production version, tried adding a course, and got notification that course didn't exist. 
![courseNotExist](https://user-images.githubusercontent.com/42220961/109576358-76228400-7aa8-11eb-94f9-fab367aa0b6d.png)

Did a bit more investigating on Heroku and noticed DB had 0 rows. I think this has to do with either the scraper since it was scheduled to automatically scrape or, that we still have over 10k rows in DB. After repopulating DB I noticed that the rows are constantly going down if you refresh in heroku.

Initially:
![overpopulatedDb](https://user-images.githubusercontent.com/42220961/109576866-66f00600-7aa9-11eb-96f4-25e63918098a.png)

Few mins later after refreshing: 
![lowerRows](https://user-images.githubusercontent.com/42220961/109578300-c5b67f00-7aab-11eb-9682-c7b34544d13f.png)

Anyways, at the moment I just called setupDb(true), to repopulate the database as a temporary fix. Haven't done too much investigation besides that.

**Comment by johnagl** [comment]
@resurreccionl Would it be okay if we got rid of prereq table for now? Looking at my local db it has over 6k rows.. I think we aren't even using it anyways? And by get rid of I just mean comment out the code that currently adds the rows to db

**Comment by resurl** [comment]
> 
> 
> @resurreccionl Would it be okay if we got rid of prereq table for now? Looking at my local db it has over 6k rows.. I think we aren't even using it anyways? And by get rid of I just mean comment out the code that currently adds the rows to db

yeah this is fine! the prereq plaintext is stored in the courses schema anyway

**Comment by jacksonyuanjx** [comment]
I'm not sure when the DB was at 0 rows but maybe the scheduled job cleared the database at the moment you were checking? I just checked right now and it looks like it's at its original size of 13,264 rows? But yea, if we can remove excess data, let's do that.

![image](https://user-images.githubusercontent.com/42788230/109580388-5b9fd900-7aaf-11eb-831f-ce8d23eb2165.png)

**Comment by johnagl** [comment]
> I'm not sure when the DB was at 0 rows but maybe the scheduled job cleared the database at the moment you were checking? I just checked right now and it looks like it's at its original size of 13,264 rows? But yea, if we can remove excess data, let's do that.
> 
> ![image](https://user-images.githubusercontent.com/42788230/109580388-5b9fd900-7aaf-11eb-831f-ce8d23eb2165.png)

Oh I fixed it, I just repopulated the db, but it was 0 a few hours ago
