### ISSUE TITLE
Create Get Started/About page

### ISSUE THREAD

**Issue by yehee** [ubclaunchpad/life-at-ubc#147]
- To explain what the application is about and how to get started
- Design inspirations?
![Screen Shot 2021-03-07 at 1 06 27 PM](https://user-images.githubusercontent.com/28884850/110254882-eff1bc00-7f45-11eb-813e-ab90350eafd1.png)
![Screen Shot 2021-03-07 at 1 08 04 PM](https://user-images.githubusercontent.com/28884850/110254930-27f8ff00-7f46-11eb-8c50-b0e8aaa7d2a8.png)
![Screen Shot 2021-03-07 at 1 08 33 PM](https://user-images.githubusercontent.com/28884850/110254948-39daa200-7f46-11eb-8eb5-0dd361bdad3a.png)

**Comment by johnagl** [comment]
Note: mockups of about/landing page in Figma
