### ISSUE TITLE
More Production DB/Backend Issues ... 

### ISSUE THREAD

**Issue by johnagl** [ubclaunchpad/life-at-ubc#149]
![moreDbIssues](https://user-images.githubusercontent.com/42220961/110258395-45829480-7f57-11eb-95de-7051e4214e5c.png)

Adding courses doesn't work again. When trying to access backend/api, the above shows up. The rows are populated on Heroku so this is different from before. 

Following articles seem useful: 
1) https://github.com/docker-library/postgres/issues/482

2) https://confluence.atlassian.com/jirakb/error-connecting-to-database-fatal-no-pg_hba-conf-entry-for-host-x-x-x-x-user-jiradbuser-database-jiradb-ssl-off-950801726.html

So far I've tried: 
1) Redeploying application
2) Restarting dynos on Heroku

**Comment by johnagl** [comment]
@jacksonyuanjx Do you mind looking into this if you have some time? :D

**Comment by jacksonyuanjx** [comment]
> @jacksonyuanjx Do you mind looking into this if you have some time? :D

Yea sure thing, I'll take a look sometime this week!
