### ISSUE TITLE
Store course section information into database

### ISSUE THREAD

**Issue by johnagl** [ubclaunchpad/life-at-ubc#25]
1. Create Table Scripts 
-  to create courses table in db
- we should check if there is already a courses table so we aren't creating it every time
2. Insert Scripts
 - to add all course information into courses table
- check if courses table exists but is empty, we don't want to keep reinserting course information 

Resources:
1) https://www.postgresqltutorial.com/postgresql-create-table/
2) https://www.postgresql.org/docs/9.5/sql-insert.html
3) https://www.postgresql.org/docs/9.1/sql-createtable.html

**Comment by johnagl** [comment]
Example from previous project. The difference with this is we just pasted these scripts into PGAdmin (postgres UI). In our case , we can't do this unless you're using PGAdmin, so I think we can do it programmatically. 

` DROP TABLE IF EXISTS Account, Activity, Address, Admin, AdminType, Availability, Chat, ChatComment, Event, Interests, 
 Profile, Region, Registered, RegularUser, Review, ReviewedBy CASCADE;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE Account(
    Email VARCHAR(100),
    Password VARCHAR(100),
    PRIMARY KEY(Email));

INSERT INTO Account
VALUES
    ('john@gmail.com', '123456'),
    ('ayman@gmail.com', '123456'),
    ('terry@gmail.com', '123456'),
    ('emma@gmail.com', '123456'),
    ('hazra@gmail.com', '123456');

CREATE TABLE Profile(
	ID uuid DEFAULT uuid_generate_v4 (),
	Email VARCHAR(100),
	DOB DATE, 
	FirstName VARCHAR(100) NOT NULL,
	LastName VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(Email) REFERENCES Account ON DELETE CASCADE);

INSERT INTO Profile
VALUES
    ('1fd87df8-7106-43b1-866c-dc8673565ae2', 'john@gmail.com', '1992-10-20', 'John', 'Aguilar'),
    ('69b734c1-d441-45ea-82fc-fae17c129294','ayman@gmail.com', '1995-02-03', 'Ayman', 'Azhar'),
    ('d31c296d-6e8d-4eb1-9fa8-1a65a8d7cbb8', 'terry@gmail.com', '1997-03-12', 'Terry', 'Zhang'),
    ('5478fb4e-2d75-4079-9ffd-7b5650e366cc', 'emma@gmail.com', '1994-12-10', 'Emma', 'Liu'),
    ('79b83a7e-2e29-4c1e-a2fe-b9c5ac4f18da', 'hazra@gmail.com', '1990-12-10', 'Hazra', 'Imran');`

**Comment by yehee** [comment]
```sql
CREATE TABLE CourseSection(
  CourseTitle VARCHAR(100),
  CourseDept VARCHAR(100),
  CourseNumber INT,
  SectionTitle VARCHAR(100),
  Status VARCHAR(100),
  Activity VARCHAR(100),
  Prof VARCHAR(100),
  Term VARCHAR(100),
  Day VARCHAR(100),
  Start DATE,
  End DATE,
  FOREIGN KEY(CourseDept, CourseNumber) REFERENCES CourseCode
);

CREATE TABLE CourseCode (
  CourseDept VARCHAR(100),
  CourseNumber INT,
  PRIMARY KEY(CourseDept, CourseNumber)
);

CREATE TABLE PreReq (
  CourseDept VARCHAR(100),
  CourseNumber INT,
  PreReqCourseDept VARCHAR(100),
  PreReqCourseNumber INT,
  FOREIGN KEY(CourseDept, CourseNumber) REFERENCES CourseCode,
  FOREIGN KEY(PreReqCourseDept, PreReqCourseNumber) REFERENCES CourseCode(CourseDept, CourseNumber),
);

CREATE TABLE CoReq (
  CourseDept VARCHAR(100),
  CourseNumber INT,
  CoReqCourseDept VARCHAR(100),
  CoReqCourseNumber INT,
  FOREIGN KEY(CourseDept, CourseNumber) REFERENCES CourseCode,
  FOREIGN KEY(CoReqCourseDept, CoReqCourseNumber) REFERENCES CourseCode(CourseDept, CourseNumber),
);
```
This is roughly the idea I have right now -- feel free to leave any comments or suggestions! I'm thinking of using UUID for the ones I haven't specified primary keys for now.

**Comment by johnagl** [comment]
> ```sql
> CREATE TABLE CourseSection(
>   CourseTitle VARCHAR(100),
>   CourseDept VARCHAR(100),
>   CourseNumber INT,
>   SectionTitle VARCHAR(100),
>   Status VARCHAR(100),
>   Activity VARCHAR(100),
>   Prof VARCHAR(100),
>   Term VARCHAR(100),
>   Day VARCHAR(100),
>   Start DATE,
>   End DATE,
>   FOREIGN KEY(CourseDept, CourseNumber) REFERENCES CourseCode
> );
> 
> CREATE TABLE CourseCode (
>   CourseDept VARCHAR(100),
>   CourseNumber INT,
>   PRIMARY KEY(CourseDept, CourseNumber)
> );
> 
> CREATE TABLE PreReq (
>   CourseDept VARCHAR(100),
>   CourseNumber INT,
>   PreReqCourseDept VARCHAR(100),
>   PreReqCourseNumber INT,
>   FOREIGN KEY(CourseDept, CourseNumber) REFERENCES CourseCode,
>   FOREIGN KEY(PreReqCourseDept, PreReqCourseNumber) REFERENCES CourseCode(CourseDept, CourseNumber),
> );
> 
> CREATE TABLE CoReq (
>   CourseDept VARCHAR(100),
>   CourseNumber INT,
>   CoReqCourseDept VARCHAR(100),
>   CoReqCourseNumber INT,
>   FOREIGN KEY(CourseDept, CourseNumber) REFERENCES CourseCode,
>   FOREIGN KEY(CoReqCourseDept, CoReqCourseNumber) REFERENCES CourseCode(CourseDept, CourseNumber),
> );
> ```
> 
> This is roughly the idea I have right now -- feel free to leave any comments or suggestions! I'm thinking of using UUID for the ones I haven't specified primary keys for now.

This looks good @yehee. I'm curious what the difference between the PreReq and CoReq table are ? I'm assuming there might be some duplicates between the 2 tables.

**Comment by yehee** [comment]
> > ```sql
> > CREATE TABLE CourseSection(
> >   CourseTitle VARCHAR(100),
> >   CourseDept VARCHAR(100),
> >   CourseNumber INT,
> >   SectionTitle VARCHAR(100),
> >   Status VARCHAR(100),
> >   Activity VARCHAR(100),
> >   Prof VARCHAR(100),
> >   Term VARCHAR(100),
> >   Day VARCHAR(100),
> >   Start DATE,
> >   End DATE,
> >   FOREIGN KEY(CourseDept, CourseNumber) REFERENCES CourseCode
> > );
> > 
> > CREATE TABLE CourseCode (
> >   CourseDept VARCHAR(100),
> >   CourseNumber INT,
> >   PRIMARY KEY(CourseDept, CourseNumber)
> > );
> > 
> > CREATE TABLE PreReq (
> >   CourseDept VARCHAR(100),
> >   CourseNumber INT,
> >   PreReqCourseDept VARCHAR(100),
> >   PreReqCourseNumber INT,
> >   FOREIGN KEY(CourseDept, CourseNumber) REFERENCES CourseCode,
> >   FOREIGN KEY(PreReqCourseDept, PreReqCourseNumber) REFERENCES CourseCode(CourseDept, CourseNumber),
> > );
> > 
> > CREATE TABLE CoReq (
> >   CourseDept VARCHAR(100),
> >   CourseNumber INT,
> >   CoReqCourseDept VARCHAR(100),
> >   CoReqCourseNumber INT,
> >   FOREIGN KEY(CourseDept, CourseNumber) REFERENCES CourseCode,
> >   FOREIGN KEY(CoReqCourseDept, CoReqCourseNumber) REFERENCES CourseCode(CourseDept, CourseNumber),
> > );
> > ```
> > 
> > 
> > This is roughly the idea I have right now -- feel free to leave any comments or suggestions! I'm thinking of using UUID for the ones I haven't specified primary keys for now.
> 
> This looks good @yehee. I'm curious what the difference between the PreReq and CoReq table are ? I'm assuming there might be some duplicates between the 2 tables.

Seems like there's a subtle difference between two:
- A prerequisite is a course that the student must have completed prior to registering for the selected course.
- A corequisite is a course that the student must take prior to or concurrently with the selected course.

What do you think?

**Comment by johnagl** [comment]
@yehee I was more so thinking along the lines that they might just be the same table because the schema is exactly the same. But I realize that we won't be able to tell the difference between a co-req and pre-req. So nevermind :D !

**Comment by johnagl** [comment]
Realized I should've posted this resource sooner: https://node-postgres.com/features/queries

We currently have a query function in the database class that can help with inserting data (might require a few tweaks).
