### ISSUE TITLE
Research on how to scrape information from SSC (Puppeteer)

### ISSUE THREAD

**Issue by johnagl** [ubclaunchpad/life-at-ubc#3]
Mentioned  Puppeteer in the meeting today, but I'm actually starting to worry about how slow it is... so I'm looking around for other solutions that are faster. Any suggestions here would be helpful, as I'm not familiar with scraping in general!

1. Puppeteer: https://github.com/puppeteer/puppeteer
2. Cheerio: https://github.com/cheeriojs/cheerio 

Focus on: Scraping all courses in Winter Term(1/2) 2020
- course code
- course title
- term (1 or 2)
- Days
- Start Time
- End Time

Don't worry too much about sanitizing the data at this point.

**Comment by resurl** [comment]
hi, i'm not too familiar with working in github teams/contributing to OSS yet so let me know if i should be posting things elsewhere or if i seem to be missing anything else! i gave the scraper a shot and this is what i have so far, but it's missing some small details so maybe this can start us off or help others in approaching the scraper in a better way? 

here's a [gist](https://gist.github.com/resurreccionl/6ab0726c149c440440f2158ec83ae777) with the code

and for every section in the course calendar, we get data that looks like this
```
{
    title: 'AANB 504 Research Methodology in Applied Animal Biology',
    code: 'AANB 504',
    status: 'Blocked',
    term: '1',
    days: ' Wed',
    start: '10:00',
    end: '13:00'
}
```

the parts i know need fixing or taking a look into are: 
1) it takes 30 mins to scrape the entire course calendar and this can probably be cut down a bit (probably not by that much though lol) if the script uses less `ElementHandle.$()` calls.
2) there are courses that span an entire year, but not all of them have the [same](https://imgur.com/aWLp1Nu) [formatting](https://imgur.com/a/ZzMK3ar), so i'm not sure how to approach that yet
3) the script ignores subjects that have no courses this term--not sure if that should be the intended behaviour or if we want to keep them too.

and probably some other things i'm forgetting at the moment! but hopefully the gist is clean enough to understand and gets us started. hope you all have a good long weekend!

**Comment by johnagl** [comment]
Nice @resurreccionl! Briefly read the code and it looks solid.

1) I agree that we probably won't be able to cut down too much on the run time, but I don't think we'll be scraping too often, so I don't think it matters? 

2) We probably need some edge cases handling for these specific cases, unless there are too many edge cases? 

3) By "this" term do you mean term 1? Or both term 1 and 2?

With regards to GitHub teams and OSS, it's new for me too. My team mostly discussed issues in person during meetings, so I'm learning as well.

**Comment by bobheadxi** [comment]
@resurreccionl that was a beautiful fantastic write up and an issue comment is the ideal location and format for this kind of exploration :)

**Comment by resurl** [comment]
@johnagl thank you!

1) oh yup, that's true! I guess this is more of a nitpicky thing or something we can do later, but I was thinking about how the data is structured and maybe it could look something more like this?

```
{
  course_title,
  course_code,
  sections: [
      {
          section_title,
          status,
          term,
          days,
          start,
          end
       }          
    ]
}
```
and that would (possibly) require less `.$()` calls but more importantly make it easier for handling the data in the db? i actually have no clue about database modelling so im just spitballing LOL.

2) i haven't looked too closely for other possible edge cases but it seems like there aren't too many, so handling them should be doable

3) i believe it's for both term 1 and term 2!

**Comment by johnagl** [comment]
> @johnagl thank you!
> 
> 1. oh yup, that's true! I guess this is more of a nitpicky thing or something we can do later, but I was thinking about how the data is structured and maybe it could look something more like this?
> 
> ```
> {
>   course_title,
>   course_code,
>   sections: [
>       {
>           section_title,
>           status,
>           term,
>           days,
>           start,
>           end
>        }          
>     ]
> }
> ```
> 
> and that would (possibly) require less `.$()` calls but more importantly make it easier for handling the data in the db? i actually have no clue about database modelling so im just spitballing LOL.
> 
> 1. i haven't looked too closely for other possible edge cases but it seems like there aren't too many, so handling them should be doable
> 2. i believe it's for both term 1 and term 2!

Let's not worry about the data structure yet until we decide on the DB. I'm still thinking about whether it's worth storing all of this course information (it gets expensive really fast because there's so many of them).

Thinking about the 30 minute scrape a bit more, I'm starting to think this is actually REALLY slow. I think Puppeteer is considerably slower than other scraping solutions because it mimics browser activity (which is slow - eg, the browser takes time to load). I'm worried about the scenario that our website is deployed, and we have to scrape ssc data, will we have to shut the entire thing down to do the scrape? I do think that the current Puppeteer scraper that you have will be useful for preliminary data, it just might not be our long term solution.

**Comment by vinnie-wu** [comment]
Definitely worth looking into this: [https://github.com/qstevens/UBC-Courses-API](url),

Considering the course schedules are updated less than quarterly, I think we should use an API like this one to call them when they're updated, and store them on a DB that we can access rather than scraping them on-demand. That gives us a lot of fluidity in modifying the existing data structure, and we can make the DB into a node that our web node can call from so we don't have to worry about the data (decoupling these would make our lives a lot easier 👯 )

Curious in how this is going to evolve!

**Comment by johnagl** [comment]
Also I think a few people have mentioned UBC courses API (there are a few of these created by students). I think these are useable in the short term for sure, especially for development purposes, and maybe even for our MVP. But I would rather us scrape the data in the long run, and store it ourselves rather than relying on an API that may or may not get maintained.

**Comment by resurl** [comment]
ok! i think it's possible to have the site stay up even as the scraper is running? for my portfolio website, I have a Heroku-hosted CMS that sends POST requests to a Netlify webhook on every change and that triggers the build script for the front-end. I'm thinking we can do the same thing for this scraper and place the POST request at the end of the scraper's main method, so whenever the scraper runs, the website still stays up and is only updated when the script is finished.

as for the db, i wonder if it doesn't have to be that expensive to store the information we need? i'm not sure that people care too much about outdated schedules, so would it be a good idea to periodically delete records that were created a long time ago (say 2-3 years)? i'm also aware that some tech companies use wide-column databases (usually apache cassandra, because its free lol) on top of another db to store historical data, so if maintaining _all_ the course schedules is something we want, we could consider using that and making it a stretch goal

**Comment by johnagl** [comment]
@resurreccionl Cool. The scraper running in the background sounds like a good solution to the 30 minute scraping problem. I think Cheerio can scrape the data much faster (almost instantaneously if it's set up correctly), but I think what you have is good. We should just use it instead of trying to optimize this early on.

As for the DB, you're right in that we would probably only need to store current course information. No one cares about making worklists for past terms anyways :D. We can probably create another issue on discussion about which database to use.

**Comment by resurreccionl** [comment]
@johnagl do you want me to push the scraper and [json file](https://gist.github.com/resurreccionl/5c9dcc2fdb67a6d89f5d1cd9156ff383) as is right now, or should i complete it before i do that?
