### ISSUE TITLE
Another solution to global state management 

### ISSUE THREAD

**Issue by aldy97** [ubclaunchpad/life-at-ubc#37]
Other than redux, a React hook: useReducer, can be used to store data used globally. I have not got to know how to use this hook exactly, but I will for sure do some research on this. It is a much less tedious way to store and manage global state comparing to  using Redux. 

P.S: I think we should try to decrease the usage of Redux/Reducer things down to minimum level

**Comment by johnagl** [comment]
Thank you !! I would go with Redux, but  I am worried because so few people know it. It's a bit of a learning curve.
