### ISSUE TITLE
Set up pre-commit to run linter and/or tests (if any)

### ISSUE THREAD

**Issue by jacksonyuanjx** [ubclaunchpad/life-at-ubc#39]
We can use a module like `husky` that runs the linters on a pre-commit git hook so that the linter runs before we even commit/push to GitHub

**Comment by aldy97** [comment]
Niiice!

**Comment by johnagl** [comment]
Another one that is fairly popular is Prettier https://prettier.io/

**Comment by resurl** [comment]
^ this & i think it's also possible to auto-fix on every save in vscode? I just didn't look into it too much when I made the automatic highlight PR, but there should be a property in `./vscode/settings.json` to automate lint fixing.

**Comment by jacksonyuanjx** [comment]
^ this & i think it's also possible to auto-fix on every save in vscode? I just didn't look into it too much when I made the automatic highlight PR, but there should be a property in `./vscode/settings.json` to automate lint fixing.

That's a good suggestion and I think we should add that in this issue's requirements! I'm not sure if everyone on the team uses vscode though so I was thinking if we set up the pre-commit hook as well, then it'll be IDE independent?

**Comment by aldy97** [comment]
Since we write it in TypeScript, I think everyone is recommended to use VScode tho

**Comment by resurl** [comment]
i think it's a good idea to just have it anyway, just so we're not locked into an editor. installing husky looks straightforward for the most part, so maybe it'd be a good issue for anyone looking for something to do?

**Comment by johnagl** [comment]
Closing this issue for now since lint/tests run on commit anyways.
