### ISSUE TITLE
Declutter README

### ISSUE THREAD

**Issue by johnagl** [ubclaunchpad/life-at-ubc#42]
README is a bit cluttered at the moment. Probably don't need all of the screenshots and code terminal information. Reorganize/remove unnecessary information. Make the server setup clearer.

**Comment by resurreccionl** [comment]
oh I was just about to ask about something related to this on the Slack LOL. regarding the docker set up, is it not necessary to also have a `DB_PORT`? I also tried to try the docker setup yesterday but I didn't know what to put for `DB_HOST`.

**Comment by johnagl** [comment]
DB_DATABASE=postgres
DB_PASSWORD=123456
DB_USER=postgres
DB_HOST=db
DB_PORT=5432
