### ISSUE TITLE
Redux set up

### ISSUE THREAD

**Issue by aldy97** [ubclaunchpad/life-at-ubc#43]
Can I start working on basic set up of Redux? Along with Redux, shall we use immutable.js in order to improve globle state predictability? I am famailiar with both of them. Shoundn't be that hard :)

**Comment by johnagl** [comment]
Sure go for it. This might be a dumb question but I'm guessing we HAVE to use redux even if we use React reducer hooks mentioned in #37 ?

**Comment by aldy97** [comment]
@johnagl  No, we donot have to use redux if we can use hook useReducer. But after watching some tutorial videos on useReducer, I found out that using useReducer is almost as tedious as using Redux to manage global state and its learning curve is even steeper than Redux. It is only sufficient when we use reducer within the scope of one component when useState is not good enough to handle inner state. Another thing is it is harder to maintain useReducer than maintaining Redux store.
