### ISSUE TITLE
es-lint with Material-UI

### ISSUE THREAD

**Issue by aldy97** [ubclaunchpad/life-at-ubc#55]
es-lint reports issues with the code that I purely copied & pasted from Material-UI sample usage of Breadcrumbs. Should I leave it there or try to fix this?
<img width="970" alt="截屏2020-10-31 下午5 55 39" src="https://user-images.githubusercontent.com/40585236/97793001-e543a680-1ba2-11eb-8e9a-f540b3799a78.png">
<img width="1083" alt="截屏2020-10-31 下午5 55 07" src="https://user-images.githubusercontent.com/40585236/97793003-e83e9700-1ba2-11eb-9916-45a0674e172c.png">

**Comment by resurl** [comment]
@aldy97 i think it might be because `"&:focus"` is in double quotes while `borderRadius` `position` etc aren't? is it possible to quote all of the property fields? i'm assuming the focus property needs to be in double quotes probably

**Comment by resurl** [comment]
for the `session` and `term` variables, it might be because there's more than one instance of a variable in scope, so you'll just need to rename one

**Comment by aldy97** [comment]
@resurreccionl  Thanks for helping! Your solutions are exactly correct for solving these issues.

**Comment by resurl** [comment]
@aldy97 glad i could help!!
