### ISSUE TITLE
My thoughs on Restriction UI 

### ISSUE THREAD

**Issue by aldy97** [ubclaunchpad/life-at-ubc#57]
I have one opinion on UI design. Rather than letting users to select days that they wanna go to school, is that more convenient for them to choose workdays that they can't? Please let me know your thoughts:)
![image](https://user-images.githubusercontent.com/40585236/97818103-3ca24f00-1c55-11eb-823d-9816bed8f771.png)

**Comment by yehee** [comment]
I second this and also thought it'd be nice if we could tell them what days they cannot possibly have a day off e.g. CPSC 415 offers only one section so they can't have a day off on MWF.

**Comment by johnagl** [comment]
Yeah, agreed, makes more sense to choose days that they dont want!
