### ISSUE TITLE
Created Schedule Grid

### ISSUE THREAD

**Issue by danielchen-pyc** [ubclaunchpad/life-at-ubc#60]
I built a schedule grid using `@syncfusion/ej2-grids` (gif attached below). Basically, I have this external `timeslot.json` file that records the row data of the timetable, which is imported to the `ScheduleGrid.tsx` file. Few things to point out though, 

1. I am having a little trouble using the MaterialUI Datagrid component because I didn't find any resources for importing external json files to the `row` field of the data grid. Any suggestions regarding this would be appreciated! 

2. From what I know, we only need to modify `timeslot.json` when the user add/delete courses and then the timetable will automatically refresh and display the current schedule?

3. In the wireframe sketch, the days are from 8:00am to 3:00pm. However, many students are taking classes after that time. In the timetable I made, I extended the hours to 5:00pm (there are still classes after 5 though). Should I make it to 9:00pm? I believe that is the latest lecture time. 

4. Another thing, the arrow button on the bottom of the page seems a little too high, leaving little space for the timetable. I made the timetable scrollable, but it still looks very crowded, especially after you add the actual classes in the blocks. Should the title be higher and the arrow be lower?

5. I'm pretty sure you can't change certain stylings of the timetable, e.g. round the edges, regardless of which UI package you use. (but I might be wrong lolll)

I didn't make a PR because I might have to change it back to Material UI. Just posting it here to make sure I'm on the right track :) 
I pushed the changes to a temporary remote `daniel` branch!

![Screen-Recording-2020-11-02-at-9](https://user-images.githubusercontent.com/50974112/97874351-d3edcc00-1d53-11eb-8c1b-9d5ce6221190.gif)

**Comment by johnagl** [comment]
> I built a schedule grid using `@syncfusion/ej2-grids` (gif attached below). Basically, I have this external `timeslot.json` file that records the row data of the timetable, which is imported to the `ScheduleGrid.tsx` file. Few things to point out though,
> 
> 1. I am having a little trouble using the MaterialUI Datagrid component because I didn't find any resources for importing external json files to the `row` field of the data grid. Any suggestions regarding this would be appreciated!
> 2. From what I know, we only need to modify `timeslot.json` when the user add/delete courses and then the timetable will automatically refresh and display the current schedule?
> 3. In the wireframe sketch, the days are from 8:00am to 3:00pm. However, many students are taking classes after that time. In the timetable I made, I extended the hours to 5:00pm (there are still classes after 5 though). Should I make it to 9:00pm? I believe that is the latest lecture time.
> 4. Another thing, the arrow button on the bottom of the page seems a little too high, leaving little space for the timetable. I made the timetable scrollable, but it still looks very crowded, especially after you add the actual classes in the blocks. Should the title be higher and the arrow be lower?
> 5. I'm pretty sure you can't change certain stylings of the timetable, e.g. round the edges, regardless of which UI package you use. (but I might be wrong lolll)
> 
> I didn't make a PR because I might have to change it back to Material UI. Just posting it here to make sure I'm on the right track :)
> I pushed the changes to a temporary remote `daniel` branch!
> 
> ![Screen-Recording-2020-11-02-at-9](https://user-images.githubusercontent.com/50974112/97874351-d3edcc00-1d53-11eb-8c1b-9d5ce6221190.gif)

What do you mean by 1 , importing external json files into a row?

**Comment by aldy97** [comment]
@danielchen-pyc hey Daniel, since APIs are under construction right now, you could make a mock response that returns JSON simulating data.

**Comment by danielchen-pyc** [comment]
I switched the package back to Material UI DataGrid and didn't import any Json files. However, I had to create two Json objects, rows and columns, to store the default time slots (first column) and the header. The code is pushed to `daniel` branch. @johnagl

**Comment by johnagl** [comment]
Good start @danielchen-pyc just took a look at your branch. If you have time we can also try adding mock course data so we can test out what the scheduler would look like with courses. Also, important to note that we will probably have a number of schedules, so we should think about how that will work (eg. pagination).

**Comment by danielchen-pyc** [comment]
Made another issue so closing this one.
