### ISSUE TITLE
API getSections does not provide course description, credits and location

### ISSUE THREAD

**Issue by aldy97** [ubclaunchpad/life-at-ubc#69]
The section schema is perfectly fine. I just think that I am not supposed to use this API to get all courses, because currently it shows a lot of duplicate "courses", which are actually sections. Another drawback of doing that is, since we are rendering around 19k rows of sections, it takes very long to get options to be loaded and its slow to respond to clicking and typing. Maybe we should have an API that only sends distinct courses with department name and course number and its corresponding info like credists, info, etc.
![image](https://user-images.githubusercontent.com/40585236/98736265-72cc8680-2359-11eb-9312-acaae34b77e1.png)
![image](https://user-images.githubusercontent.com/40585236/98736313-7fe97580-2359-11eb-9e7f-f3530f4a7f78.png)

```typescript
interface Section {
  coursetitle: string;
  coursedept: string;
  coursenumber: string;
  sectiontitle: string;
  status: string;
  activity: string;
  prof: string;
  term: string;
  day: string;
  starttime: string;
  endtime: string;
}

  const fetchAllCourses = async () => {
    const coursesFetched = await axios.get(
      'http://localhost:5000/api/sections'
    );
    const sectionLists: Section[] = coursesFetched.data;
    let courseList: string[] = [];
    for (let course of sectionLists) {
      const fullName = course.coursedept + ' ' + course.coursenumber;
      courseList.push(fullName);
    }
    setCoursesPool(courseList);
    setIsLoaded(true);
  };
```

**Comment by yehee** [comment]
@aldy97 Sure thing! Shouldn't take too long I believe, and seems like the schema hasn't been updated as well. I can pick those up if you need me to. Thanks for pointing those out!

**Comment by resurl** [comment]
most of this (except for location) has been implemented with the change from section -> course endpoints so we can probably close this?

**Comment by yehee** [comment]
@resurreccionl Agreed!
