### ISSUE TITLE
Create Template for PR's 

### ISSUE THREAD

**Issue by johnagl** [ubclaunchpad/life-at-ubc#7]
Pull requests should have a template that developers can fill in. See examples of closed PR's in Launch Pad docs https://github.com/ubclaunchpad/docs/pulls?q=is%3Apr+is%3Aclosed

**Comment by danielchen-pyc** [comment]
For the PR template, do I just add a `.github` folder and put the `.md` PR template file in it? Or should I post the template here first?

**Comment by danielchen-pyc** [comment]
# Changes
- Change summary/description
- Any @mention 's

# Related Tickets
- Closes #ticketnum

# Checklist
- [ ] Spelling is good
- [ ] `make` or `make lint` ran successfully
- [ ] I've read the [Structuring Content](https://docs.ubclaunchpad.com/CONTRIBUTING#structuring-content) guide
- [ ] I've read up on our [Pull Request checks](https://docs.ubclaunchpad.com/CONTRIBUTING#checks)

**Comment by johnagl** [comment]
This looks good @danielchen-pyc !!. There's a way to set this up on Github so that whenever anyone tries to do a pull request, they'll see this template and just have to fill it in!

**Comment by danielchen-pyc** [comment]
Hello @johnagl ! Can you please take a look if this looks good? I'll add them to a .github folder if they are ready.

**Comment by johnagl** [comment]
This looks good! I would leave the the checklist empty for now, since we don't really have a checklist just yet. We can add these in the future.

**Comment by danielchen-pyc** [comment]
Thank you! So I'll remove the four items in the checklist and add it to the `.github` folder in the repo?

**Comment by danielchen-pyc** [comment]
# Changes
- Change summary/description
- Any @mention 's

# Related Tickets
- Closes #ticketnum

# Checklist

**Comment by johnagl** [comment]
> Thank you! So I'll remove the four items in the checklist and add it to the `.github` folder in the repo?

Yes I think that works! Not sure if the PR template .md file  has to be named something specific (eg. `pull_request_template.md`). See https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by bobheadxi** [comment]
Three are examples in the handbook that indicate they have a required naming scheme: https://docs.ubclaunchpad.com/handbook/project-management/repositories#repository-templates

https://sourcegraph.com/search?q=repo:ubclaunchpad/*+file:_TEMPLATE+&patternType=regexp

Pull request templates specifically: https://sourcegraph.com/search?q=repo:ubclaunchpad/*+file:PULL_REQUEST_TEMPLATE+&patternType=regexp

One suggestion would be to put the placeholders (eg "change summary") in markdown comments (so that you don't have to delete them every time):

```md
<--- my comment -->
```

some of the templates should have examples of this

**Comment by danielchen-pyc** [comment]
Thank you for all the feedback! I will upload the file but it says I need to create a new branch. How should I proceed? @johnagl  Thank you!

**Comment by johnagl** [comment]
> Thank you for all the feedback! I will upload the file but it says I need to create a new branch. How should I proceed? @johnagl Thank you!

See #13 issue on learning Git and Git workflows. Read the docs linked, and do the practice exercise!

**Comment by danielchen-pyc** [comment]
Sorry I should leave a comment before closing. Close #7 since #26 added PR template successfully.
