### ISSUE TITLE
UI enhancement for adding courses

### ISSUE THREAD

**Issue by yehee** [ubclaunchpad/life-at-ubc#76]
Hi all! This would be more of an enhancement that would come later once we have a fully working application, but I was wondering if it's worth considering of using [chips](https://material-ui.com/components/chips/) on Material UI for selecting courses on courses tab:
![Screen Shot 2020-11-15 at 2 21 02 AM](https://user-images.githubusercontent.com/28884850/99182322-36967e80-26e9-11eb-971e-03fa0b57b4e1.png)

**Comment by aldy97** [comment]
@yehee I think it is totally a good idea! But yeah as you have tagged it really isnt the core part of the project. It is for sure I will look into that later on!

**Comment by yehee** [comment]
Closing it for now :D
