### ISSUE TITLE
Discussion: Which database should we use?

### ISSUE THREAD

**Issue by johnagl** [ubclaunchpad/life-at-ubc#8]
We talked about this a little bit on Saturday but didn't really get into too much depth so I thought we could probably continue some of the discussion here. I'm hoping we can decide on our database before our next meeting this Saturday (October 17) so that one of the dev tasks can be to add the database to the existing backend. 

Right now our choices are primarily
1) MongoDB 
2) PostgreSQL

Open to others as well.

**Comment by johnagl** [comment]
I'm no database expert by any means, but leaning towards MongoDB because of it's flexibility with schemas. Depending on what features we add, our data models will change and MongoDB does this well compared to SQL databases.

**Comment by vinnie-wu** [comment]
Not sure if using a MongoDB is a good idea after the scraping stage is over. For initial data scraping it would get the job done but we eventually have to write a schema for the data (judging from what we have now, data we need would be just the stuff like course timeslot, instructors, etc...). PostgreSQL has a JSONB you can kick off with that and eventually move over to a normal SQL after the project decisions are crystalized. But if we start off with MongoDB the database migration would be a nightmare if anytime we want to try out a new DB.

**Comment by vinnie-wu** [comment]
Also do we want to make the DB a separate node from the web node? It would decouple the architecture but idk how that would be to set up on the Netlify deployment guide we use 😕

**Comment by bobheadxi** [comment]
The DB should probably not be accessed from your client-side web application (ie what you deploy on Netlify), so Netlify doesn't come into play here - your choice of database would likely be tied to your server's deployment method.

the approach I recommend would be to use a docker-compose setup for your server + database for now, and worry about properly deploying the database later - at least one other team is doing this, you can try asking in the #ask-for-help channel!

**Comment by aldy97** [comment]
Since there is basically no relations between one course and another except for pre-req, I think it would be better if we use NoSQL like firebase or MongoDB. It is also advantageous for front-end ppl to have easier processing on JSON format files. You guys have mentioned deployment variation due to different choice of db, idk abbout this part because I merely focus on front-end only :)

**Comment by jacksonyuanjx** [comment]
From a small discussion w/ John, it sounds like we're not planning to manage user accounts at least for this MVP. So if we're only looking to store the course data, I think we might be better off serving the data or subcategories of the data over a CDN. This will reduce the requests made and would be a lot cheaper than managing/hosting a DB.

**Comment by bobheadxi** [comment]
This is a stretch, but since course reqs and course groups (by spec, year level, etc) are a graph-type data, you could try a proper graph database like https://github.com/cayleygraph/cayley - graph query languages make for some interesting opportunities, and standardized graph data formats make it easy to set up visualization out of the box 😀 I've [worked on this before](https://bobheadxi.dev/riot-games/#alert-visualisation) so if anyone is curious about this option feel free to ping me on Slack!

**Comment by johnagl** [comment]
> The DB should probably not be accessed from your client-side web application (ie what you deploy on Netlify), so Netlify doesn't come into play here - your choice of database would likely be tied to your server's deployment method.
> 
> the approach I recommend would be to use a docker-compose setup for your server + database for now, and worry about properly deploying the database later - at least one other team is doing this, you can try asking in the #ask-for-help channel!

This is what I was thinking as well. @vinnie-wu our server and client are separate at the moment. DB will most likely be integrated with server. And we will probably deploy frontend and server/db separately.

**Comment by vinnie-wu** [comment]
> > The DB should probably not be accessed from your client-side web application (ie what you deploy on Netlify), so Netlify doesn't come into play here - your choice of database would likely be tied to your server's deployment method.
> > the approach I recommend would be to use a docker-compose setup for your server + database for now, and worry about properly deploying the database later - at least one other team is doing this, you can try asking in the #ask-for-help channel!
> 
> This is what I was thinking as well. @vinnie-wu our server and client are separate at the moment. DB will most likely be integrated with server. And we will probably deploy frontend and server/db separately.

Okay that sounds good. Definitely should keep them separated (decoupling them is best practice 🥇).

**Comment by bobheadxi** [comment]
@johnagl what was the decision here?
