### ISSUE TITLE
Stop repopulating database on server restart

### ISSUE THREAD

**Issue by johnagl** [ubclaunchpad/life-at-ubc#82]
Right now, our server automatically repopulates database upon server restart. Figure out a better strategy for when we should repopulate database.

**Comment by aldy97** [comment]
Would that be a issue if we deploy our current service?

**Comment by danielchen-pyc** [comment]
Just to clarify, the database repopulates by calling `populateDb()` in `setupDb()`, in `setup.ts`. Do we just need to figure out a better time to repopulate the database than when server restarts?
